"""create actions, risk_assessments, approvals, audit_records

Revision ID: 473900d668ec
Revises: 
Create Date: 2026-08-19 22:51:33.805817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '473900d668ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('params_hash', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_actions_agent_id_created_at', 'actions', ['agent_id', 'created_at'], unique=False)
    op.create_table('audit_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prev_hash', sa.String(), nullable=False),
    sa.Column('entry_hash', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_records_created_at', 'audit_records', ['created_at'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=True),
    sa.Column('approved_params_hash', sa.String(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approvals_action_id', 'approvals', ['action_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('reversibility_score', sa.Float(), nullable=False),
    sa.Column('data_scope_score', sa.Float(), nullable=False),
    sa.Column('regulatory_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('weights_version', sa.String(), nullable=False),
    sa.Column('composite', sa.Float(), nullable=False),
    sa.Column('floor_fired', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('llm_latency_ms', sa.Integer(), nullable=True),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('rendered_explanation', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_assessments')
    op.drop_index('ix_approvals_action_id', table_name='approvals')
    op.drop_table('approvals')
    op.drop_index('ix_audit_records_created_at', table_name='audit_records')
    op.drop_table('audit_records')
    op.drop_index('ix_actions_agent_id_created_at', table_name='actions')
    op.drop_table('actions')
    # ### end Alembic commands ###
