"""add state to actions

Revision ID: c5326268c7fa
Revises: 473900d668ec
Create Date: 2026-08-20 01:07:39.931947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5326268c7fa'
down_revision: Union[str, None] = '473900d668ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('state', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actions', 'state')
    # ### end Alembic commands ###
